name: Notion Stock Update

on:
  schedule:
    # 깃허브 서버는 UTC 시간 기준 (한국시간 KST - 9시간)
    - cron: '0 0 * * *'   # 한국 시간 09:00 (국내 개장)
    - cron: '30 6 * * *'  # 한국 시간 15:30 (국내 마감)
    - cron: '30 13 * * *' # 한국 시간 22:30 (미국 개장)
    - cron: '0 20 * * *'  # 한국 시간 05:00 (미국 마감)
  workflow_dispatch: # 내가 원할 때 수동으로 바로 실행할 수 있는 버튼

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'Stock_bot/requirements.txt'

      - name: Install dependencies
        run: pip install -r Stock_bot/requirements.txt

      - name: Run script
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: python Stock_bot/update_price.py
